[package]
name = "Inspect It!"
description = "A variety of objects can be inspected."
homepage = "https://www.nexusmods.com/morrowind/mods/*****"
repository = "https://github.com/longod/InspectIt"
authors = ["longod"]
version = "1.0"

[dependencies]
assets = [
    "shaders\\XEshaders\\InspectIt",
]

[dependencies.mwse]
buildnumber = 3786

[dependencies.mge-xe]
version = ">=0.15.0"
