[package]
name = "Inspect It!"
description = "Inspect a variety of objects."
homepage = "https://www.nexusmods.com/morrowind/mods/54636"
repository = "https://github.com/longod/InspectIt"
authors = ["longod"]
version = "1.6"

[dependencies]
assets = [
    "Meshes\\InspectIt",
    "shaders\\XEshaders\\InspectIt",
]

[dependencies.mwse]
buildnumber = 3940

[dependencies.mge-xe]
version = ">=0.15.0"
